### ISSUE TITLE
tests hang on Windows

### ISSUE THREAD

**Issue by chorny** [mudler/Mojo-IOLoop-ReadWriteProcess#1]
03_func.t:
```
# Subtest: _new_err
    ok 1
    ok 2
    1..2
ok 1 - _new_err
# Subtest: write_pidfile
    ok 1
    1..1
ok 2 - write_pidfile
# Subtest: _fork
Can't use an undefined value as filehandle reference at lib/Mojo/IOLoop/ReadWriteProcess.pm line 229.
(hangs)
```
If your module cannot work on Windows at all, you can die in Makefile.PL/Build.PL. See http://wiki.cpantesters.org/wiki/CPANAuthorNotes for how to do this.

**Comment by mudler** [comment]
Will look at it and try to not ditch support for Windows. But i don't have a machine with Windows to test on it, so in worst case i'll just let it die for windows builds. Thanks for reporting

**Comment by mudler** [comment]
Can you confirm that after https://github.com/mudler/Mojo-IOLoop-ReadWriteProcess/commit/448f7196d66ef1a42f68506ae8790eefd5d7d835 the test get skipped? thanks

**Comment by chorny** [comment]
Yes, tests no longer hang. Other tests have non-zero exit code when running `Build test`, but I don't see any problems when running standalone.

**Comment by mudler** [comment]
Thanks, when will have spare time will check out test errors that breaks compatibility with Windows systems, maybe setting up AppVeyor would help.
