### ISSUE TITLE
The tests in t/10_cgroupv* use invalid paths

### ISSUE THREAD

**Issue by eseyman** [mudler/Mojo-IOLoop-ReadWriteProcess#4]
The tests in t/10_cgroupv* use invalid paths. This wasn't a huge problem until Mojolicious 8.23 was released. In that version, Mojo::File was modified not to allow undefined values in paths.

This breaks the tests in t/10_cgroupv*.

**Comment by okurz** [comment]
Also see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939460 about this
